Depth Anything V2 - UDAV2 depth Preprocessor
Mikubill/sd-webui-controlnet pull request #2969
Opened 2024-07-01 05:42 UTC by MackinationsAi

I've made the necessary updates for the depth_anything_v2 preprocessor to function properly (I've done multiple tests & it's working great!). After this I will be uploading the new depth_anything_v2 hf transformers.

2024-07-01 10:51 UTC, MackinationsAi commented
For the time being, please use this transformers .whl that I put together for testing - https://github.com/MackinationsAi/sd-webui-controlnet/releases/tag/transformers-4.44.1.dev0. (I'm still working on getting the transformers uploaded)

2024-07-01 11:33 UTC, sdbds commented
![image](https://github.com/Mikubill/sd-webui-controlnet/assets/8085926/c0a33532-d944-4519-9fff-d51e1ee821e3)
Looks like no problem, now we just need to wait for the transformer to be adapted

2024-07-01 15:20 UTC, kagevazquez commented
if you set resize_target to True and adjust the height and width to 1036 in depth_anything_v2.py you get even better results.
![Untitled](https://github.com/Mikubill/sd-webui-controlnet/assets/1572367/06e30d3c-8c5b-46e7-ac13-25dfa7e01700)
![Untitled1](https://github.com/Mikubill/sd-webui-controlnet/assets/1572367/fe1cbf41-18b1-423d-85c3-cbc0d843b8c4)

2024-07-01 21:19 UTC, huchenlei requested changes

2024-07-01 21:19 UTC, huchenlei commented on annotator/depth_anything_v2.py
> +            "https://huggingface.co/MackinationsAi/Depth-Anything-V2_Safetensors/blob/main/depth_anything_v2_vitl.safetensors",
"blob" => "resolve"
Otherwise you download an HTML file.

2024-07-03 17:10 UTC, huchenlei commented
Continued in https://github.com/Mikubill/sd-webui-controlnet/pull/2977. I don't have the push access to your branch @MackinationsAi

2024-07-03 17:10 UTC, closed without merging

2024-07-24 11:29 UTC, zthrx commented
Hi, 

How to solve this problem? 

SUPER SD 2.0 Dependencies\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\depth_anything_v2.py", line 9, in <module>
    from depth_anything_v2.dpt import DepthAnythingV2
ModuleNotFoundError: No module named 'depth_anything_v2.dpt'


Cheers!

2024-07-25 02:03 UTC, MackinationsAi commented
@zthrx it looks like the depth_anything_v2.dpt module which is installed from the depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl didn't properly install on your end. I just removed my sd-webui-controlnet extension & reinstalled it to see if the same error would happen for me which it didn't. So my advice would be to remove & reinstall sd-webui-controlnet. You should be good after that. If the issue persists open up an [issue ticket](https://github.com/Mikubill/sd-webui-controlnet/issues/new) & @ tag me so I can assist you further.

2024-07-25 07:29 UTC, zthrx commented
> @zthrx it looks like the depth_anything_v2.dpt module which is installed from the depth_anything_v2-2024.7.1.0-py2.py3-none-any.whl didn't properly install on your end. I just removed my sd-webui-controlnet extension & reinstalled it to see if the same error would happen for me which it didn't. So my advice would be to remove & reinstall sd-webui-controlnet. You should be good after that. If the issue persists open up an [issue ticket](https://github.com/Mikubill/sd-webui-controlnet/issues/new) & @ tag me so I can assist you further.

Hey, 
Thank you for fast reply! I have a noob question, how to properly remove/reinstall this extension since I have 50gb of models. Should I remove entire folder only? 

Cheers!

2024-07-25 19:20 UTC, MackinationsAi commented
@zthrx move the models folder somewhere else on your machine, delete the sd-webui-control folder in extensions. (Just to make sure & to be clear, I am **NOT** saying to delete your controlnet models folder in the main models folder. If your models are here - [move this folder](https://github.com/Mikubill/sd-webui-controlnet/tree/main/models) out of the sd-webui-controlnet extensions folder before deleting it). Then its a simple matter of opening up a1111 & reinstalling sd-webui-controlnet from the extensions tab & restart a1111, then move all of your models back into that folder I linked above.

2024-07-26 17:29 UTC, zthrx commented
> @zthrx move the models folder somewhere else on your machine, delete the sd-webui-control folder in extensions. (Just to make sure & to be clear, I am **NOT** saying to delete your controlnet models folder in the main models folder. If your models are here - [move this folder](https://github.com/Mikubill/sd-webui-controlnet/tree/main/models) out of the sd-webui-controlnet extensions folder before deleting it). Then its a simple matter of opening up a1111 & reinstalling sd-webui-controlnet from the extensions tab & restart a1111, then move all of your models back into that folder I linked above.

Hey, 

Thank you for your time by helping me. Unfortunately after reinstalling I keep getting this error. Other preprocessors like Depth_anything or midas works fine. 

I've started new topic: 
https://github.com/Mikubill/sd-webui-controlnet/issues/3018

Cheers!